### ISSUE TITLE
Refactor code using a SearchProvider trait

### ISSUE THREAD

**Issue by rnestler** [rnestler/rust-torrent-search#2]
Currently we use two simple functions. Ideally we would use a [trait](https://doc.rust-lang.org/book/traits.html) `SearchProvider` which defines a function `search(keyword: &str) -> Vec<Torrent>`. This would then be implemented for a `struct PirateBaySearch{}`.
For someone to get started:
 - [x] Change code to use a `fn search(&str) ->Vec<Torrent>` function which creates the search URL (see [strings](https://doc.rust-lang.org/book/strings.html#concatenation))
 - [x] Add `SearchProvider` trait (see [traits](https://doc.rust-lang.org/book/traits.html))
 - [x] Add `PirateBaySearch` struct containing the hyper connection

**Comment by rnestler** [comment]
@ubruhin Maybe you want to get started with that one?

**Comment by ubruhin** [comment]
Here is my pull request: #5 

I have also split the project into multiple files/modules, but I'm not sure if I made it properly...
What do you say?

**Comment by rnestler** [comment]
With the merge of #5 I consider this closed.
