### ISSUE TITLE
Linuxu Ubuntu 18.04 - VirtualBox VM

### ISSUE THREAD

**Issue by creptt** [rnestler/rust-torrent-search#37]
I cloned the project, install openssl accordingly and ran cargo.
it did not build/compile; however when I attempted it on MacBook pro 2018 it worked.

**Comment by rnestler** [comment]
Can you share the error you got on Ubuntu?

**Comment by rnestler** [comment]
@creptt Any update on this?

**Comment by creptt** [comment]
nestler, neveremind, it worked. thanks!

**Comment by rnestler** [comment]
Closing then :slightly_smiling_face:
