### ISSUE TITLE
Major versions of dependencies

### ISSUE THREAD

**Issue by billyb2** [rnestler/rust-torrent-search#43]
How would you feel about always using the latest non-breaking version of all dependencies. For example, using every release of percent-encoding version 2 instead of one specific release, or the same with tokio 0.2

**Comment by rnestler** [comment]
I like to have the `Cargo.lock` under version control to have reproducible builds. This is a best practice for Rust applications as described in https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries.

But I can run `cargo update` more often to get the latest non-breaking version of dependencies in the future.

**Comment by billyb2** [comment]
Oh alright, thank you. I didn't know much about this.

**Comment by rnestler** [comment]
Closing, since not really an issue.
